### PR TITLE
Added assertions

### PR DESCRIPTION
**Pull request by nayuta-gondo**

### CODE REVIEW

**Comment by practicalswift** [comment]
Assertions are removed when Python is started with the `-O` options. Please adjust your code so that it works equivalently under `-O` :-)

**Comment by nayuta-gondo** [comment]
`assert` is the test itself in py.test.
py.test overwrites `assert` and the `-O` options can not remove it.

**Review by cdecker — APPROVED** [review]
ACK d05fb0f4f236d8b4f9087316ae8c84c3c99e3b48

**Comment by practicalswift** [comment]
@nayuta-gondo Ah, got it! Thanks for clarifying! :-)

**Pull request merged**
